#!/bin/bash -i
set -e


# update and install dependenices
sudo apt-get update && sudo apt-get upgrade \
    && sudo apt-get install -y python3 python3-pip git


# try a clone if it doesn't exist, if it does go and pull that repo
dir_bak="$(pwd)"
git clone https://github.com/sierra-alpha/kaianga-conf.git \
    || cd kaianga-conf && git pull && cd "$dir_bak"


# (change to real pypi eventually)
# Need to add python stuff to the path, and install kaianga,
# Run Kaianga the multithreaded script runner to setup our env
pip3 install -U -i https://test.pypi.org/simple kaianga
"$(python3 -m site --user-base)"/bin/kaianga -c ~/kaianga-conf/kaianga.conf -i -l debug -u shaun >> kaianga.log 2&>1


# our kaianga-conf starts emacs --daemon as part of its config
# Launch emacs, after all thats why where here right ;)
emacsclient -c -a ""
