#!/bin/bash

# update and install dependenices
sudo apt-get update && sudo apt-get upgrade \
    && sudo apt-get install -y python3 python3-pip git


dir_bak="$(pwd)"
git clone https://github.com/sierra-alpha/kaianga-conf.git \
    || cd kaianga-conf && git pull && cd "$dir_bak"

export PATH=\"$(python3 -m site --user-base)/bin:$PATH\"
pip3 install -U -i https://test.pypi.org/simple kaianga

kaianga -c ~/kaianga-conf/kaianga.conf -i -l debug -u shaun

emacsclient -c -a emacs

